// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ghostface-home/AliasFocus.tsx": () => import("../components/mockups/ghostface-home/AliasFocus.tsx"),
  "./components/mockups/ghostface-home/Cockpit.tsx": () => import("../components/mockups/ghostface-home/Cockpit.tsx"),
  "./components/mockups/ghostface-home/CommandDeck.tsx": () => import("../components/mockups/ghostface-home/CommandDeck.tsx"),
  "./components/mockups/ghostface-home/Ledger.tsx": () => import("../components/mockups/ghostface-home/Ledger.tsx"),
  "./components/mockups/ghostface-home/SplitIdentity.tsx": () => import("../components/mockups/ghostface-home/SplitIdentity.tsx"),
  "./components/mockups/ghostface-home/SplitIdentityElevated.tsx": () => import("../components/mockups/ghostface-home/SplitIdentityElevated.tsx"),
  "./components/mockups/ghostface-home/SplitIdentityTight.tsx": () => import("../components/mockups/ghostface-home/SplitIdentityTight.tsx"),
  "./components/mockups/ghostface-home/Vault.tsx": () => import("../components/mockups/ghostface-home/Vault.tsx")
};
